---
title: "Airbnb Research"
author: "Zhiyi Chen and Zhuo Zhuo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

This project is inspired by ........


System".[]https://insideairbnb

>"
Citi Bike is a privately owned public bicycle sharing system serving the New York City boroughs of the Bronx, Brooklyn, Manhattan, and Queens, as well as Jersey City, New Jersey. Named after lead sponsor Citigroup, it is operated by Motivate (formerly Alta Bicycle Share), with former Metropolitan Transportation Authority CEO Jay Walder as chief executive until September 30, 2018[1] when the company was acquired by Lyft. The system's bikes and stations use BIXI-branded technology from PBSC Urban Solutions.
>First proposed in 2008 by the New York City Department of Transportation, Citi Bike's scheduled 2011 opening was delayed by Hurricane Sandy and technological problems. It officially opened in May 2013 with 332 stations and 6,000 bikes. Annual expansions have brought the totals to 706 stations and 12,000 bikes as of October 2017, making the service the largest bike sharing program in the United States. Further expansions for Citi Bike are planned to extend its service area across the Bronx, Brooklyn, Manhattan, and Queens, and increase the number of bikes to 40,000."
>--[Wiki Link]https://en.wikipedia.org/wiki.

In 2020, due to the COVID 19 Pandemic, New York City implemented the lock down and social distance policy. Many Companies requires employees to work from home instead of going to office everyday. We want to analyze the pandemic's influence on New York City residents, specially for 1.6M Manhattan residents who use Citi Bike as part of their commute tools.

In our project, we will research on different topics:

1. Eg1

2. The Membership analysis (Age, Gender, Annual memberships or Subscriber)

3. Time Series 

4. W

5. Eg 5

6.  users'pattern 

7. Top 5 most 



